### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by davidfou**
I found some problems on your plugin, so I rewrite a part of it.

⚠️  depreciation: the option path is not the same now, it's relative to the output folder

### CODE REVIEW

**Comment by davidfou** [comment]
🆙

**Comment by davidfou** [comment]
Is this repo dead?

**Comment by davidfou** [comment]
Someone here?

**Comment by davidfou** [comment]
If you don't mind, could you please add me as a collaborator? People use your package but it needs to be fixed...

**Comment by bobbibg** [comment]
Apologies! Only just noticed this on the back of the email from npm. Have added you as a collaborator. Many thanks!

**Comment by davidfou** [comment]
Perfect, thanks :)

**Pull request merged**
